validate:
  image: gramener/builderrors
  script: builderrors

deploy:
  stage: deploy
  script: deploy
  variables:
    SERVER: gramener.com
    URL: builderrors
    VERSION: static
  environment:
    name: production
    url: https://gramener.com/builderrors/
